'use client';
import {useEffect,useState} from 'react';import {API} from '@/lib/api';import {Check,LogOut,Save,Trash2,Upload} from 'lucide-react';
export default function Admin(){const[token,setToken]=useState('');const[data,setData]=useState<any>(null);const[msg,setMsg]=useState('');
 useEffect(()=>{const t=localStorage.getItem('revel_token')||'';setToken(t);if(t)load(t)},[]);
 async function load(t=token){const r=await fetch(`${API}/admin/dashboard`,{headers:{Authorization:`Bearer ${t}`}});if(r.ok)setData(await r.json());else logout()}
 async function login(e:any){e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(r.ok){localStorage.setItem('revel_token',d.token);setToken(d.token);load(d.token)}else setMsg(d.message)}
 function logout(){localStorage.removeItem('revel_token');setToken('');setData(null)}
 async function req(url:string,options:any={}){
  try{
   const r=await fetch(`${API}${url}`,{...options,headers:{Authorization:`Bearer ${token}`,...options.headers}});
   if(r.ok){setMsg('Alteração salva com sucesso.');await load();return true;}
   const error=await r.json().catch(()=>null);
   setMsg(error?.message||`Não foi possível concluir. Erro ${r.status}.`);
   return false;
  }catch{
   setMsg('Não foi possível conectar ao servidor.');
   return false;
  }
 }
 if(!token)return <main className="grid min-h-screen place-items-center p-5"><form onSubmit={login} className="glass w-full max-w-md rounded-3xl p-8"><h1 className="text-3xl font-black">Painel Revel Mix</h1><input name="email" type="email" required className="input mt-6" placeholder="E-mail"/><input name="password" type="password" required className="input mt-3" placeholder="Senha"/><button className="btn btn-gold mt-5 w-full">Entrar</button>{msg&&<p className="mt-4 text-gold">{msg}</p>}</form></main>;
 if(!data)return <main className="grid min-h-screen place-items-center">Carregando...</main>;
 return <main className="min-h-screen p-5 md:p-10"><div className="container-site"><header className="flex items-center justify-between"><div><span className="text-gold">ADMINISTRAÇÃO</span><h1 className="text-4xl font-black">Painel Revel Mix</h1></div><button onClick={logout} className="btn btn-ghost"><LogOut size={18}/> Sair</button></header>{msg&&<p className="mt-5 rounded-xl bg-gold/10 p-3 text-gold">{msg}</p>}
 <section className="mt-10"><h2 className="text-2xl font-bold">Serviços e preços</h2><div className="mt-4 grid gap-4 lg:grid-cols-3">{data.services.map((s:any)=><form key={s.id} className="glass rounded-2xl p-5" onSubmit={e=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));req(`/admin/services/${s.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,pricePerM2:Number(f.pricePerM2),active:true})})}}><input name="title" className="input" defaultValue={s.title}/><textarea name="description" className="input mt-3 min-h-28" defaultValue={s.description}/><input name="pricePerM2" type="number" step=".01" className="input mt-3" defaultValue={s.pricePerM2}/><button className="btn btn-gold mt-3"><Save size={16}/> Salvar</button></form>)}</div></section>
 <section className="mt-10"><h2 className="text-2xl font-bold">Upload para galeria</h2><form className="glass mt-4 flex flex-col gap-3 rounded-2xl p-5 md:flex-row" onSubmit={e=>{e.preventDefault();req('/admin/gallery',{method:'POST',body:new FormData(e.currentTarget)})}}><input name="title" className="input" placeholder="Título"/><select name="category" className="input"><option value="URETANO">Uretano</option><option value="EPOXI">Epóxi</option><option value="TECNOCIMENTO">Tecnocimento</option></select><input name="image" type="file" accept="image/*" required className="input"/><button className="btn btn-gold"><Upload size={16}/> Enviar</button></form><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.gallery.map((g:any)=><div className="glass overflow-hidden rounded-2xl" key={g.id}><img src={g.url} className="h-36 w-full object-cover"/><button onClick={()=>req(`/admin/gallery/${g.id}`,{method:'DELETE'})} className="m-3 text-red-400"><Trash2/></button></div>)}</div></section>
 <section className="mt-10"><h2 className="text-2xl font-bold">Avaliações</h2><div className="mt-4 space-y-3">{data.reviews.map((r:any)=><div className="glass rounded-2xl p-5" key={r.id}><b>{r.name} • {r.rating}/5</b><p className="mt-2 text-zinc-400">{r.comment}</p><textarea id={`resp-${r.id}`} className="input mt-3" defaultValue={r.response||''} placeholder="Resposta opcional"/><div className="mt-3 flex flex-wrap gap-2"><button type="button" className="btn btn-gold" onClick={()=>req(`/admin/reviews/${r.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'APPROVED',response:(document.getElementById(`resp-${r.id}`) as HTMLTextAreaElement).value||null})})}><Check size={16}/> Aprovar</button><button type="button" className="btn btn-ghost" onClick={()=>req(`/admin/reviews/${r.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'REJECTED'})})}>Rejeitar</button><button type="button" className="btn btn-ghost text-red-400" onClick={()=>req(`/admin/reviews/${r.id}`,{method:'DELETE'})}><Trash2 size={16}/> Excluir</button></div></div>)}</div></section>
 <section className="mt-10"><h2 className="text-2xl font-bold">Mensagens recebidas</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-gold"><th className="p-3">Cliente</th><th>Contato</th><th>Serviço</th><th>Mensagem</th></tr></thead><tbody>{data.messages.map((m:any)=><tr className="border-t border-white/10" key={m.id}><td className="p-3">{m.name}</td><td>{m.phone}<br/>{m.email}</td><td>{m.serviceType}<br/>{m.area?`${m.area} m²`:''}</td><td className="max-w-md p-3">{m.message}</td></tr>)}</tbody></table></div></section>
 </div></main>}
