'use client';
import {useMemo,useState} from 'react';
import {motion} from 'framer-motion';
import {ArrowRight,CheckCircle2,Instagram,Mail,Menu,Phone,ShieldCheck,Sparkles,Star,Upload,X} from 'lucide-react';
import {Gallery,Item} from 'react-photoswipe-gallery';
import 'photoswipe/dist/photoswipe.css';
import {API} from '@/lib/api';

type Service={id:number;slug:string;title:string;description:string;pricePerM2:number}; type Img={id:number;url:string;title?:string;category:string};
const wa='https://wa.me/5511963123807?text='+encodeURIComponent('Olá! Gostaria de solicitar um orçamento para um revestimento da Revel Mix Revestimentos.');
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.65}};
export default function Site({data}:{data:any}){
 const services:Service[]=data.services; const gallery:Img[]=data.gallery; const reviews=data.reviews; const [menu,setMenu]=useState(false); const [category,setCategory]=useState('TODOS'); const [service,setService]=useState(services[0]?.slug||'uretano'); const [area,setArea]=useState(10); const [result,setResult]=useState<number|null>(null); const filtered=category==='TODOS'?gallery:gallery.filter(g=>g.category===category);
 const price=useMemo(()=>services.find(s=>s.slug===service)?.pricePerM2||0,[services,service]);
 async function post(endpoint:string,form:HTMLFormElement,setMsg:(v:string)=>void){const obj:Record<string,any>=Object.fromEntries(new FormData(form)); if(endpoint==='reviews')obj.rating=Number(obj.rating); if(endpoint==='contact')obj.area=obj.area?Number(obj.area):null; const r=await fetch(`${API}/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});const d=await r.json();setMsg(d.message||'Não foi possível enviar.');if(r.ok)form.reset();}
 return <main className="overflow-hidden">
 <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/70 backdrop-blur-xl"><div className="container-site flex h-20 items-center justify-between px-5"><a href="#home" className="text-xl font-black tracking-widest gold-text">REVEL MIX</a><nav className="hidden gap-7 text-sm md:flex">{['Sobre','Serviços','Galeria','Orçamento','Avaliações','Contato'].map(x=><a className="hover:text-gold" key={x} href={`#${x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}`}>{x}</a>)}</nav><button className="md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="glass mx-4 mb-4 rounded-2xl p-5 md:hidden">{['Sobre','Serviços','Galeria','Orçamento','Avaliações','Contato'].map(x=><a onClick={()=>setMenu(false)} className="block py-3" key={x} href={`#${x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}`}>{x}</a>)}</div>}</header>
 <section id="home" className="relative flex min-h-screen items-center bg-[radial-gradient(circle_at_top_right,rgba(199,165,87,.25),transparent_35%),linear-gradient(rgba(0,0,0,.55),rgba(0,0,0,.9)),url('/images/epoxi/hero.jpeg')] bg-cover bg-center"><div className="container-site px-5 pt-24"><motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.9}} className="max-w-4xl"><span className="mb-5 inline-flex rounded-full border border-gold/40 bg-gold/10 px-4 py-2 text-sm text-gold">Desde 2008 • Excelência em revestimentos</span><h1 className="text-5xl font-black leading-[.95] md:text-8xl">REVEL MIX<br/><span className="gold-text">REVESTIMENTOS LTDA</span></h1><p className="mt-7 max-w-2xl text-lg text-zinc-300 md:text-xl">Especialistas em revestimentos industriais e residenciais desde 2008. Qualidade, resistência e acabamento impecável para transformar qualquer ambiente.</p><div className="mt-9 flex flex-wrap gap-3"><a className="btn btn-gold" href="#contato">Solicitar Orçamento <ArrowRight size={18}/></a><a className="btn btn-ghost" href="#servicos">Conheça nossos Serviços</a><a className="btn btn-ghost" href="#galeria">Ver Galeria</a><a className="btn btn-ghost" href={wa} target="_blank">Falar no WhatsApp</a></div></motion.div></div></section>
 <section id="sobre" className="section"><motion.div {...reveal} className="container-site grid items-center gap-10 lg:grid-cols-2"><div><span className="text-gold">SOBRE A EMPRESA</span><h2 className="mt-3 text-4xl font-black md:text-6xl">Experiência que sustenta cada projeto.</h2><div className="mt-6 space-y-4 text-zinc-400"><p>A Revel Mix Revestimentos Ltda atua desde 2008 oferecendo soluções completas em revestimentos industriais e residenciais. Nossa empresa se destaca pela qualidade dos materiais utilizados, mão de obra especializada e compromisso com a excelência em cada projeto.</p><p>Trabalhamos com tecnologias modernas para oferecer pisos resistentes, duráveis e de alto padrão, atendendo desde pequenas reformas até grandes obras industriais.</p><p>Nosso compromisso é entregar qualidade, segurança, inovação e total satisfação aos nossos clientes.</p></div></div><div className="glass min-h-[430px] rounded-[2rem] bg-[linear-gradient(rgba(0,0,0,.15),rgba(0,0,0,.65)),url('/images/uretano/institucional.jpeg')] bg-cover bg-center shadow-gold"/></motion.div></section>
 <section id="servicos" className="section bg-zinc-950"><div className="container-site"><motion.div {...reveal}><span className="text-gold">SERVIÇOS</span><h2 className="mt-3 text-4xl font-black md:text-6xl">Soluções de alto desempenho.</h2></motion.div><div className="mt-10 grid gap-5 lg:grid-cols-3">{services.map((s,i)=><motion.article {...reveal} transition={{duration:.5,delay:i*.1}} key={s.id} className="glass rounded-[2rem] p-7 hover:-translate-y-2 hover:border-gold/50 transition"><Sparkles className="text-gold"/><h3 className="mt-8 text-2xl font-bold">{s.title}</h3><p className="mt-4 min-h-28 text-zinc-400">{s.description}</p><div className="mt-7 border-t border-white/10 pt-5"><small className="text-zinc-500">Valor estimado</small><p className="text-2xl font-black text-gold">R$ {Number(s.pricePerM2).toFixed(2).replace('.',',')} / m²</p></div></motion.article>)}</div></div></section>
 <section id="galeria" className="section"><div className="container-site"><motion.div {...reveal}><span className="text-gold">GALERIA</span><h2 className="mt-3 text-4xl font-black md:text-6xl">Trabalhos realizados.</h2><div className="mt-7 flex flex-wrap gap-2">{['TODOS','URETANO','EPOXI','TECNOCIMENTO'].map(c=><button onClick={()=>setCategory(c)} className={`btn ${category===c?'btn-gold':'btn-ghost'}`} key={c}>{c}</button>)}</div></motion.div>{filtered.length?<Gallery><div className="mt-8 grid auto-rows-[240px] gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((g,i)=><Item key={g.id} original={g.url} thumbnail={g.url} width="1600" height="1200">{({ref,open})=><a ref={ref} onClick={open} className={`${i%5===0?'md:row-span-2':''} cursor-zoom-in overflow-hidden rounded-3xl`}><img loading="lazy" src={g.url} alt={g.title||'Trabalho Revel Mix'} className="h-full w-full object-cover transition duration-500 hover:scale-110"/></a>}</Item>)}</div></Gallery>:<div className="glass mt-8 rounded-3xl p-10 text-center text-zinc-400">Nenhuma imagem foi encontrada nas pastas da galeria.</div>}</div></section>
 <section id="orcamento" className="section bg-zinc-950"><motion.div {...reveal} className="container-site grid gap-10 lg:grid-cols-2"><div><span className="text-gold">CALCULADORA</span><h2 className="mt-3 text-4xl font-black md:text-6xl">Estime seu investimento.</h2><p className="mt-5 text-zinc-400">Tenha uma referência inicial rápida antes de solicitar a avaliação técnica.</p></div><div className="glass rounded-[2rem] p-7"><label>Tipo de revestimento</label><select className="input mt-2" value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s.id} value={s.slug}>{s.title}</option>)}</select><label className="mt-5 block">Área em metros quadrados</label><input className="input mt-2" type="number" min="1" value={area} onChange={e=>setArea(Number(e.target.value))}/><button className="btn btn-gold mt-6 w-full" onClick={()=>setResult(area*price)}>Calcular Orçamento</button>{result!==null&&<div className="mt-6 rounded-2xl bg-gold/10 p-5"><small>Valor estimado</small><p className="text-4xl font-black text-gold">{result.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p></div>}<p className="mt-5 text-xs leading-relaxed text-zinc-500">Este valor é apenas uma estimativa. O orçamento final poderá variar conforme as condições do local, preparação da superfície, materiais necessários e complexidade do serviço. Entre em contato com a Revel Mix Revestimentos para receber um orçamento personalizado.</p></div></motion.div></section>
 <section className="section"><div className="container-site"><motion.div {...reveal} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{['Empresa fundada em 2008','Atendimento especializado','Equipe qualificada','Materiais de alta qualidade','Alta durabilidade','Garantia dos serviços','Atendimento residencial e industrial','Orçamento rápido','Acabamento de alto padrão'].map(x=><div className="glass flex items-center gap-3 rounded-2xl p-5" key={x}><CheckCircle2 className="text-gold"/>{x}</div>)}</motion.div></div></section>
 <section className="section bg-[radial-gradient(circle_at_center,rgba(199,165,87,.18),transparent_55%)]"><motion.div {...reveal} className="container-site glass rounded-[2.5rem] p-10 text-center"><Instagram className="mx-auto text-gold" size={42}/><h2 className="mt-5 text-4xl font-black">Acompanhe nossos trabalhos</h2><p className="mt-3 text-zinc-400">Veja novos projetos, bastidores e acabamentos no Instagram oficial.</p><a className="btn btn-gold mt-7" target="_blank" href="https://www.instagram.com/revestimento_de_piso_epoxi/">Seguir no Instagram</a></motion.div></section>
 <Reviews reviews={reviews} post={post}/><Contact post={post}/>
 <footer className="border-t border-white/10 px-5 py-10"><div className="container-site flex flex-col justify-between gap-5 text-sm text-zinc-500 md:flex-row"><div><b className="text-white">Revel Mix Revestimentos Ltda</b><br/>Desde 2008 • © 2026 Todos os direitos reservados.</div><div>Desenvolvido por <b className="text-gold">Lauan de Lima Gomes</b></div></div></footer>
 <a aria-label="WhatsApp" href={wa} target="_blank" className="fixed bottom-5 right-5 z-50 flex h-16 w-16 items-center justify-center rounded-full bg-green-500 text-white shadow-2xl"><Phone/></a>
 </main>
}
function Reviews({reviews,post}:{reviews:any[];post:any}){const[msg,setMsg]=useState('');return <section id="avaliacoes" className="section bg-zinc-950"><div className="container-site grid gap-10 lg:grid-cols-2"><motion.div {...reveal}><span className="text-gold">AVALIAÇÕES</span><h2 className="mt-3 text-4xl font-black md:text-6xl">Compartilhe sua experiência.</h2><div className="mt-7 space-y-4">{reviews.slice(0,3).map(r=><div className="glass rounded-2xl p-5" key={r.id}><div className="flex text-gold">{Array.from({length:r.rating}).map((_,i)=><Star fill="currentColor" size={16} key={i}/>)}</div><p className="mt-3">“{r.comment}”</p><small className="text-zinc-500">{r.name}{r.city?` • ${r.city}`:''}</small>{r.response&&<p className="mt-3 border-l-2 border-gold pl-3 text-sm text-zinc-400">Resposta da Revel Mix: {r.response}</p>}</div>)}</div></motion.div><form className="glass rounded-[2rem] p-7" onSubmit={e=>{e.preventDefault();post('reviews',e.currentTarget,setMsg)}}><input name="name" required className="input" placeholder="Nome"/><input name="city" className="input mt-3" placeholder="Cidade (opcional)"/><select name="rating" className="input mt-3" defaultValue="5"><option value="5">5 estrelas</option><option value="4">4 estrelas</option><option value="3">3 estrelas</option><option value="2">2 estrelas</option><option value="1">1 estrela</option></select><textarea name="comment" required minLength={10} className="input mt-3 min-h-36" placeholder="Comentário"/><button className="btn btn-gold mt-5 w-full">Enviar Avaliação</button>{msg&&<p className="mt-4 text-sm text-gold">{msg}</p>}</form></div></section>}
function Contact({post}:{post:any}){const[msg,setMsg]=useState('');return <section id="contato" className="section"><div className="container-site grid gap-10 lg:grid-cols-2"><motion.div {...reveal}><span className="text-gold">CONTATO</span><h2 className="mt-3 text-4xl font-black md:text-6xl">Vamos transformar seu espaço.</h2><div className="mt-7 space-y-4"><a href={wa} target="_blank" className="glass flex items-center gap-4 rounded-2xl p-5"><Phone className="text-gold"/> (11) 96312-3807</a><a href="mailto:Rivelmixrevestimentos@gmail.com" className="glass flex items-center gap-4 rounded-2xl p-5"><Mail className="text-gold"/> Rivelmixrevestimentos@gmail.com</a></div><div className="mt-5 flex gap-3"><a className="btn btn-gold" href={wa} target="_blank">Falar no WhatsApp</a><a className="btn btn-ghost" href="mailto:Rivelmixrevestimentos@gmail.com">Enviar E-mail</a></div></motion.div><form className="glass rounded-[2rem] p-7" onSubmit={e=>{e.preventDefault();post('contact',e.currentTarget,setMsg)}}><input name="name" required className="input" placeholder="Nome"/><div className="grid gap-3 md:grid-cols-2"><input name="phone" required className="input mt-3" placeholder="Telefone"/><input name="email" type="email" required className="input mt-3" placeholder="E-mail"/></div><select name="serviceType" className="input mt-3"><option>Uretano</option><option>Piso Epóxi</option><option>Tecnocimento</option></select><input name="area" type="number" min="0" className="input mt-3" placeholder="Área aproximada (m²)"/><textarea name="message" required className="input mt-3 min-h-32" placeholder="Mensagem"/><button className="btn btn-gold mt-5 w-full">Solicitar Orçamento</button>{msg&&<p className="mt-4 text-sm text-gold">{msg}</p>}</form></div></section>}
