export const metadata={title:'Termos de Uso | Revel Mix Revestimentos',description:'Condições de uso do site e regras aplicáveis às estimativas e solicitações de orçamento.'};
const sections=[
 ['1. Uso do site','Este site apresenta informações institucionais, serviços, trabalhos realizados, estimativas de preço, avaliações e canais de contato da Revel Mix Revestimentos Ltda. O usuário deve utilizá-lo de forma lícita, responsável e sem tentar comprometer sua segurança ou funcionamento.'],
 ['2. Estimativas de orçamento','Os valores exibidos na calculadora são apenas estimativas iniciais. O preço definitivo depende de avaliação técnica, condições e preparação da superfície, metragem confirmada, materiais, localização, logística, prazo e complexidade do serviço.'],
 ['3. Contratação e execução','O envio de formulário ou mensagem não constitui contratação automática. Escopo, preço, prazo, garantia, forma de pagamento e demais condições serão definidos em proposta ou contrato específico aceito pelas partes.'],
 ['4. Prazos e disponibilidade','Prazos de visita, orçamento e execução podem variar conforme agenda, tamanho da obra, acesso ao local, condições climáticas, disponibilidade de materiais e outros fatores operacionais.'],
 ['5. Garantias','As garantias aplicáveis serão informadas na proposta ou no contrato, considerando o tipo de revestimento, condições do substrato, uso do ambiente, manutenção e demais requisitos técnicos.'],
 ['6. Imagens e conteúdo','Fotos, textos, identidade visual e demais conteúdos do site são protegidos pela legislação aplicável. É proibida sua reprodução comercial ou alteração sem autorização, salvo usos permitidos por lei.'],
 ['7. Avaliações','O usuário é responsável pelo conteúdo enviado. Avaliações podem ser moderadas, rejeitadas ou excluídas quando contiverem linguagem ofensiva, dados de terceiros, publicidade, conteúdo ilegal, falso ou sem relação com o serviço.'],
 ['8. Links externos','Links para WhatsApp, Instagram, e-mail ou outros serviços são disponibilizados para conveniência. O uso dessas plataformas está sujeito aos termos e políticas dos respectivos fornecedores.'],
 ['9. Privacidade','O tratamento de dados pessoais é descrito na Política de Privacidade. Ao utilizar os formulários, o usuário declara ter lido as informações apresentadas e fornecido dados verdadeiros.'],
 ['10. Atualizações','A Revel Mix poderá atualizar preços, informações, funcionalidades e estes termos sem aviso prévio. A versão vigente será a publicada nesta página.'],
 ['11. Contato','Dúvidas podem ser encaminhadas para Rivelmixrevestimentos@gmail.com ou pelo telefone/WhatsApp (11) 96312-3807.']
];
export default function Termos(){return <main className="min-h-screen px-5 py-24"><article className="container-site glass rounded-[2rem] p-8 md:p-14"><a href="/" className="text-gold">← Voltar ao site</a><p className="mt-6 text-sm font-bold uppercase tracking-widest text-gold">Condições de utilização</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Termos de Uso</h1><p className="mt-5 text-zinc-400">Última atualização: 15 de julho de 2026.</p><div className="mt-10 space-y-8">{sections.map(([title,text])=><section key={title}><h2 className="text-2xl font-bold">{title}</h2><p className="mt-3 leading-7 text-zinc-300">{text}</p></section>)}</div><div className="mt-10 flex flex-wrap gap-3"><a href="/politica-de-privacidade" className="btn btn-gold">Política de Privacidade</a><a href="/lgpd" className="btn btn-ghost">Sobre a LGPD</a></div></article></main>}
