export const metadata={title:'Política de Privacidade | Revel Mix Revestimentos',description:'Saiba como a Revel Mix coleta, utiliza, armazena e protege dados pessoais.'};
const sections=[
 ['1. Quem somos','A Revel Mix Revestimentos Ltda é responsável pelas decisões sobre o tratamento dos dados pessoais coletados neste site. Para assuntos de privacidade, utilize o e-mail Rivelmixrevestimentos@gmail.com ou o telefone/WhatsApp (11) 96312-3807.'],
 ['2. Dados que podemos coletar','Nos formulários de orçamento e contato, podemos coletar nome, telefone, e-mail, tipo de serviço, área aproximada e mensagem. No formulário de avaliação, podemos coletar nome, cidade, nota e comentário. Dados técnicos essenciais de acesso podem ser tratados para segurança e funcionamento do site.'],
 ['3. Finalidades do tratamento','Usamos os dados para responder solicitações, elaborar e acompanhar orçamentos, prestar atendimento, moderar e publicar avaliações autorizadas, prevenir abusos, proteger o site e cumprir obrigações legais ou regulatórias.'],
 ['4. Bases legais','O tratamento poderá ocorrer para atender a pedido do titular antes da contratação, executar contrato, cumprir obrigação legal ou regulatória, exercer direitos, atender interesses legítimos compatíveis com a expectativa do titular e, quando aplicável, com base no consentimento.'],
 ['5. Compartilhamento','Os dados não são vendidos. Poderão ser compartilhados apenas com fornecedores necessários à operação do site e do atendimento, como hospedagem, banco de dados, e-mail e WhatsApp, sempre limitados à finalidade do serviço, ou com autoridades quando houver obrigação legal.'],
 ['6. Armazenamento e segurança','Mantemos os dados pelo período necessário às finalidades informadas, ao atendimento, à defesa de direitos e ao cumprimento de obrigações legais. Adotamos medidas técnicas e administrativas razoáveis para reduzir riscos de acesso não autorizado, perda, alteração ou divulgação indevida.'],
 ['7. Direitos do titular','Você pode solicitar confirmação de tratamento, acesso, correção, informação sobre compartilhamento, anonimização, bloqueio ou eliminação quando cabível, portabilidade conforme regulamentação, revisão de decisões automatizadas quando existentes e revogação do consentimento. Algumas solicitações podem ser limitadas por obrigação legal ou necessidade de conservação para exercício de direitos.'],
 ['8. Avaliações publicadas','Avaliações só são exibidas após moderação. Ao enviar uma avaliação, o titular declara que o conteúdo é verdadeiro e não viola direitos de terceiros. Nome, cidade, nota, comentário e eventual resposta da empresa poderão ser publicados após aprovação.'],
 ['9. Links e serviços de terceiros','O site contém links para Instagram, WhatsApp e e-mail. Ao acessá-los, o tratamento de dados passa também a seguir as políticas dessas plataformas.'],
 ['10. Cookies','Atualmente o site pode utilizar apenas recursos técnicos necessários ao seu funcionamento. Caso sejam implantados cookies de análise, publicidade ou tecnologias semelhantes, este aviso será atualizado e, quando necessário, será solicitado consentimento específico.'],
 ['11. Alterações desta política','Esta política poderá ser atualizada para refletir mudanças legais, técnicas ou operacionais. A versão vigente ficará disponível nesta página com a data de atualização.'],
 ['12. Contato sobre dados pessoais','Para exercer direitos ou esclarecer dúvidas sobre privacidade, envie uma mensagem para Rivelmixrevestimentos@gmail.com com o assunto “LGPD – Dados Pessoais”. Poderemos solicitar informações adicionais para confirmar a identidade do solicitante.']
];
export default function Politica(){return <main className="min-h-screen px-5 py-24"><article className="container-site glass rounded-[2rem] p-8 md:p-14"><a href="/" className="text-gold">← Voltar ao site</a><p className="mt-6 text-sm font-bold uppercase tracking-widest text-gold">Privacidade e proteção de dados</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Política de Privacidade</h1><p className="mt-5 max-w-3xl text-zinc-400">Última atualização: 15 de julho de 2026. Este documento explica, de forma clara, como os dados pessoais enviados pelo site são tratados.</p><div className="mt-10 space-y-8">{sections.map(([title,text])=><section key={title}><h2 className="text-2xl font-bold text-white">{title}</h2><p className="mt-3 leading-7 text-zinc-300">{text}</p></section>)}</div><p className="mt-10 rounded-2xl border border-gold/30 bg-gold/10 p-5 text-sm text-zinc-300">Este texto é um modelo informativo para a operação descrita no site e deve ser revisado sempre que houver mudança no uso de dados, fornecedores ou tecnologias.</p></article></main>}
